### GET ALL DATA
GET http://localhost:8081/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTYxNzQ2NTMsImV4cCI6MTY1NjE3NTU1M30.BuVI_37ESTdWntph9AIp0EfJCjzNG04Te4W18vXfm8s
### GET ONE DATA
GET http://localhost:8081/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTYxNzQ2NTMsImV4cCI6MTY1NjE3NTU1M30.BuVI_37ESTdWntph9AIp0EfJCjzNG04Te4W18vXfm8s

### CREATE DATA
POST http://localhost:8081/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTMyOTIwODUsImV4cCI6MTY1MzI5Mjk4NX0.w0wM7JGx4XInETenGNTBmltouRU8gHXFV6qfXmZZG0I
Content-Type: application/json

{
    "username":"username",
    "password":"password",
    "user_nama":"User Test"
}

### UPDATE DATA
PUT http://localhost:8081/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTMyOTIwODUsImV4cCI6MTY1MzI5Mjk4NX0.w0wM7JGx4XInETenGNTBmltouRU8gHXFV6qfXmZZG0I
Content-Type: application/json

{
    "username":"username",
    "password":"password",
    "user_nama":"User Test"
}

### DELETE DATA

DELETE http://localhost:8081/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTMyOTE3NzIsImV4cCI6MTY1MzI5MjY3Mn0.cXyTd92fs-e1QMLjC4y-CgVm4rXSb6PsmG_6GOBarto

### AUTHENTICATE
POST http://localhost:8081/api/auth
Content-Type: application/json

{
   "username":"layhome12",
   "password":"password"
}

### REFRESH TOKEN
GET http://localhost:8081/api/auth/refresh

### LOGOUT
GET http://localhost:8081/api/logout


